function(add_productive_sources)
    target_sources(
        hardware_lib
        PRIVATE src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_comp.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cordic.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_crc.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_crc_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cryp.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cryp_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fmac.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_hrtim.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2s.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_irda.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_iwdg.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_lptim.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_nand.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_nor.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_qspi.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rng.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sai.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sai_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_smartcard.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_smartcard_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_smbus.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_smbus_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sram.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_usart.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_usart_ex.c
                src/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_wwdg.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_comp.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_cordic.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_crc.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_crs.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dac.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dma.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_exti.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_fmac.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_fmc.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_gpio.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_hrtim.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_i2c.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_lptim.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_lpuart.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_opamp.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_pwr.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_rcc.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_rng.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_rtc.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_spi.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_tim.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_ucpd.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usart.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usb.c
                #src/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_utils.c
    )
endfunction()
